development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  cable:
    allowed_request_origins:
      - http://ec2-18-140-62-35.ap-southeast-1.compute.amazonaws.com:3000
      - https://chat.warongit.tech
  channel_prefix: MessagesChannel
